import {
  GYEONGBOKGUNG,
  GYEONGBOKGUNG02,
  GYEONGBOKGUNG03,
  SEOUL01,
  SEOUL02,
  SEOUL03,
  HANOKMAEUL02,
  HANOKMAEUL,
  INSADONG,
} from '../../assets';
const SAMPLEYOUTUBES = [
  {
    id: 1,
    toggleDisplay: true,
    name: 'PopularLocations',
    title: 'Taekwondowon, a versatile location for film and TV',
    url: 'https://www.youtube.com/embed/joiGm8xre04',
    subtitle:
      'Discover the charms of Muju Taekwondowon a special filming location of South Korea',
    text: `Discover the charms of Muju Taekwondowon a special filming location of South Korea`,
    thumbnailPath: GYEONGBOKGUNG,
    contentId: '1',
    baseUrl: '/produce-in-korea/popular-locations',
    tags: ['popular-location'],
  },
  {
    id: 2,
    toggleDisplay: true,
    name: 'PopularLocations',
    title: 'Establishing Seoul city',
    url: 'https://www.youtube.com/embed/-pMNJLlUTYU',
    subtitle: 'Establishing Seoul city as background of your film',
    text: `Establishing Seoul city as background of your film`,
    thumbnailPath: GYEONGBOKGUNG02,
    contentId: '2',
    baseUrl: '/produce-in-korea/popular-locations',
    tags: ['popular-location'],
  },
  {
    id: 3,
    toggleDisplay: true,
    name: 'Korea from the sky',
    title: 'Korea from the sky',
    url: 'https://www.youtube.com/embed/2LekFOqnrOA',
    subtitle: `Seoul and many other beautiful locations of South Korea from the sky`,
    text: `Seoul and many other beautiful locations of South Korea from the sky`,
    thumbnailPath: HANOKMAEUL,
    contentId: '3',
    baseUrl: '/produce-in-korea/popular-locations',
    tags: ['popular-location'],
  },
  // {
  //   id: 4,
  //   toggleDisplay: false,
  //   name: 'Seoul Film Commission & Korean Film Commissions',
  //   title: 'Seoul Film Commission & Korean Film Commissions',
  //   url: 'https://www.youtube.com/embed/G5AQGM22Xa8',
  //   subtitle: `What film commissions can do for international filmmakers and producers to shoot in South Korea and much more`,
  //   text: `What film commissions can do for international filmmakers and producers to shoot in South Korea and much more`,
  //   thumbnailPath: HANOKMAEUL,
  //   contentId: '4',
  //   baseUrl: '/produce-in-korea/popular-locations',
  //   tags: ['location-incentive'],
  // },
  {
    id: 4,
    toggleDisplay: true,
    name: 'Pechino Express by local producer',
    title: 'Pechino Express by local producer',
    url: 'https://www.youtube.com/embed/SVWezoYUqM0',
    text: `Korean producer reveals how Pechino Express, an Italian reality show was produced in South Korea`,
    subtitle: `Korean producer reveals how Pechino Express, an Italian reality show was produced in South Korea`,
    thumbnailPath: INSADONG,
    contentId: '4',
    baseUrl: '/produce-in-korea/popular-locations',
    tags: ['location-incentive'],
  },
  // {
  //   id: 2,
  //   title: 'Welcome to Busan!',
  //   url: 'https://www.youtube.com/embed/GGLwsq6o8Ng',
  //   text: `Busan, formerly romanized as Pusan and now officially known as Busan Metropolitan City, is South Korea's second-most populous city after Seoul, with a population of over approximately 3.4 million inhabitants.[3] It is the economic, cultural and educational center of southeastern South Korea, with its port—Korea's busiest and the fifth-busiest in the world—only about 193 kilometers (120 mi) from Japanese islands of Kyushu and Honshu. The surrounding "Southeast Economic Zone" (including Ulsan and South Gyeongsang) is South Korea's largest industrial area.

  //         Busan is divided into 15 major administrative districts and a single county, together housing a population of approximately 3.6 million. The full metropolitan area, the Southeastern Maritime Industrial Region, has a population of approximately 8 million. The most densely built-up areas of the city are situated in a number of narrow valleys between the Nakdong and the Suyeong Rivers, with mountains separating most of the districts. The Nakdong is Korea's longest river and Busan's Haeundae Beach is also the country's largest.`,
  // },
];

export default SAMPLEYOUTUBES;
